name:                haskell-jsession-bot
version:             0.1.0.0
github:              "githubuser/haskell-jsession-bot"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/haskell-jsession-bot#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - Crypto
    - bytestring
    - uri-encode
    - time
    - random
    - base64-bytestring
    - http-conduit
    - mtl
    - aeson
    - unordered-containers
    - text
    - utf8-string

executables:
  haskell-jsession-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-jsession-bot
    - http-conduit
    - bytestring
    - conduit
    - aeson
    - unordered-containers
    - text
    - mtl


tests:
  haskell-jsession-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-jsession-bot
    - hspec
